name: Run Python Script

on:
  workflow_dispatch:  # Allows manual trigger of the workflow
  schedule:           # Scheduled trigger
    - cron: "*/5 * * * *"  # Run every 5 minutes
jobs:
  run-script:
    runs-on: ubuntu-latest  # Runs on the latest version of Ubuntu

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # This will check out your repository's code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the latest available Python version

    - name: Install dependencies
      run: |
        pip install pandas boto3 selenium  # Install dependencies listed in requirements.txt

    - name: Run Python script
      run: |
        python code.py  # Replace this with the name of your Python script (e.g., code.py)
